export const mockData = [
  {
    id: 1,
    name: "Mod-duler Project",
    startDate: "Monday, 13/12/21",
    endDate: "Thrusday, 30/12/21",
    description: "Project scheduling website coding",
    owner: "Dummy User",
    members: [
      {
        name: "Dummy User",
        role: "Project Manager",
        email: "dummy@mail.com",
      },
      {
        name: "Mai",
        role: "Member",
        email: "mai@gmail.com",
      },
      {
        name: "Mew",
        role: "Member",
        email: "mew@email.com",
      },
      {
        name: "Jeen",
        role: "Member",
        email: "jeen@mail.com",
      },
    ],
    tasks: [
      {
        id: 1,
        name: "Coding Important features",
        description: "Coding item in priority 1&2",
        startDate: "9/10/21",
        endDate: "Tuesday, 23/11/21",
        status: false,
        assignTo: "Mai",
      },
      {
        id: 2,
        name: "Database",
        description: "Design and create database",
        startDate: "2/11/21",
        endDate: "Friday, 26/11/21",
        status: true,
        assignTo: "Dummy User",
      },
      {
        id: 3,
        name: "Preparation",
        description: "Preparation before coding",
        startDate: "5/10/21",
        endDate: "Tuesday, 19/10/21",
        status: true,
        assignTo: "Mew",
      },
      {
        id: 4,
        name: "Problem Definition",
        description: "use Diagram for Design",
        startDate: "9/10/21",
        endDate: "Tuesday, 12/10/21",
        status: false,
        assignTo: "Mew",
      },
    ],
  },
  {
    id: 2,
    name: "OS VDO",
    startDate: "Wednesday, 17/11/21",
    endDate: "Wednesday, 01/12/21",
    description: "VDO Presentation: How to compile linux kernel",
    owner: "Dummy User",
    members: [
      {
        name: "Dummy User",
        role: "Project Manager",
        email: "dummy@mail.com",
      },
      {
        name: "Mew",
        role: "Member",
        email: "mew@email.com",
      },
      {
        name: "Jeen",
        role: "Member",
        email: "jeen@mail.com",
      },
    ],
    tasks: [
      {
        id: 1,
        name: "Record Tutorial",
        description: "first part of VDO",
        startDate: "21/11/21",
        endDate: "Friday, 26/11/21",
        status: false,
        assignTo: "Mew",
      },
      {
        id: 2,
        name: "Record sound",
        description: "Record main description sound for VDO",
        startDate: "21/11/21",
        endDate: "Friday, 26/11/21",
        status: true,
        assignTo: "Dummy User",
      },
      {
        id: 3,
        name: "Research",
        description: "find information for VDO",
        startDate: "17/11/21",
        endDate: "Saturday, 20/11/21",
        status: true,
        assignTo: "Dummy User",
      },
    ],
  },
  {
    id: 3,
    name: "GEN241 Project",
    startDate: "Friday, 01/10/21",
    endDate: "Tuesday, 30/11/21",
    description: "Music Arrangement Project",
    owner: "Jeen",
    members: [
      {
        name: "Jeen",
        role: "Project Manager",
        email: "jeen@mail.com",
      },
      {
        name: "Dummy User",
        role: "Member",
        email: "dummy@email.com",
      },
      {
        name: "Mew",
        role: "Member",
        email: "mew@mail.com",
      },
    ],
    tasks: [
      {
        id: 1,
        name: "Music",
        description: "Music",
        startDate: "7/10/21",
        endDate: "Friday, 05/11/21",
        status: false,
        assignTo: "Mew",
      },
      {
        id: 2,
        name: "Record sound",
        description: "Record main description sound for VDO",
        startDate: "5/11/21",
        endDate: "Tuesday, 30/11/21",
        status: true,
        assignTo: "Jeen",
      },
    ],
  },
];
